# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hello.HelloRequest" do
    optional :name, :string, 1
    optional :age, :int32, 2
  end
  add_message "hello.HelloResponse" do
    optional :name, :string, 1
    optional :age, :int32, 2
  end
end

module Hello
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloResponse").msgclass
end
